#!/usr/bin/python3
#/usr/bin/env python
# -*- coding: utf-8 -*-

# Authors:
# Rocío López-Anguita (rlanguit@ujaen.es)
# Arturo Montejo-Ráez (amontejo@ujaen.es)
# Centro de Estudios Avanzados en TIC (CEATIC)
# Universidad de Jaén
# 2018

import json
import os
from ComplexityLanguage import ComplexityLanguage
from ComplexitySpanish import ComplexitySpanish
from ComplexityEnglish import ComplexityEnglish
from ComplexityFrench import ComplexityFrench
from ComplexityPolish import ComplexityPolish
from ComplexityItalian import ComplexityItalian
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from sklearn.decomposition import PCA
from sklearn import preprocessing
import argparse

parser = argparse.ArgumentParser(description='PAN2018 author identificator based on text complexity metrics')
parser.add_argument('-i', type=string, help='input directory')
parser.add_argument('-o', type=string, help='output directory')
args = parser.parse_args()
print(args.i, args.o)
exit()
print('Loading complexity analyzers for different languages...\n', flush=True)
mlComplexityText = {
    'en': ComplexityEnglish(),
    'sp': ComplexitySpanish(),
    'fr': ComplexityFrench(),
    'pl': ComplexityPolish(),
    'it': ComplexityItalian()
}

INPUT_DIR = args.i
OUTPUT_DIR = args.o
with open(INPUT_DIR+'/collection-info.json', 'r') as f:      
    collectionInfo = json.load(f)  
    f.close()
print(type(collectionInfo))